name: Release Kotlin Project

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The release version to create (e.g., 1.0.0)'
        required: true
      next_snapshot_version:
        description: 'The next snapshot version (e.g., 1.0.1-SNAPSHOT)'
        required: true

jobs:
  release:
    name: "Release Kotlin Project ${{ github.event.inputs.release_version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Configure git for commit/push"
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: "Set release version ${{ github.event.inputs.release_version }}"
        run: |
          ./gradlew setVersion -PnewVersion="${{ github.event.inputs.release_version }}"
          git add "library/version.properties"
          git commit -m "Release version ${{ github.event.inputs.release_version }}"

      - name: "Create Git tag v${{ github.event.inputs.release_version }}"
        run: |
          release_version="${{ github.event.inputs.release_version }}"
          git tag -a "v${release_version}" -m "Release ${release_version}"
          git push origin "v${release_version}"

      - name: "Set next snapshot version ${{ github.event.inputs.next_snapshot_version }}"
        run: |
          ./gradlew setVersion -PnewVersion=${{ github.event.inputs.next_snapshot_version }}
          git add "library/version.properties"
          git commit -m "Set next snapshot version ${{ github.event.inputs.next_snapshot_version }}"
          git push
