name: Release Kotlin Project

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_FOR_GIT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Configure git for commit/push"
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: "Set release version"
        run: |
          ./gradlew releaseVersion
          version=$(./gradlew getVersion | grep "Version: " | sed -e 's/^Version: //')
          echo "RELEASE_VERSION=${version}" >> "${GITHUB_ENV}"

          git add "library/version.properties"
          git commit -m "Release version ${version}"

      - name: "Create Git tag v${{ env.RELEASE_VERSION }}"
        run: |
          release_version="${{ env.RELEASE_VERSION }}"
          git tag -a "v${release_version}" -m "Release ${release_version}"
          git push origin "v${release_version}"

      - name: "Set next snapshot version"
        run: |
          ./gradlew setNextPrereleaseVersion
          version=$(./gradlew getVersion | grep "Version: " | sed -e 's/^Version: //')
          git add "library/version.properties"
          git commit -m "Set next snapshot version ${version}"
          git push
